[package]
name = "sumatra_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
sumatra_parser = { path = "../parser" }
sumatra_vm = { path = "../vm"}
env_logger = "0.11.5"
log = { workspace = true }
